import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { PlaitBoard, PlaitElement } from '@plait/core';
import type { BoardStyleSchemeOption, SelectedElementsSummary } from '../types';
import { boardStyleService } from '../services/board-style-service';
import {
  applyStyleToElements,
  createStyleSnapshot,
  restoreStyleSnapshot,
} from '../utils/board-style-application';

export interface UseBoardStyleOptimizationOptions {
  board: PlaitBoard;
  targetElements: PlaitElement[];
  selectionSummary: SelectedElementsSummary;
  autoGenerate?: boolean;
}

export interface UseBoardStyleOptimizationResult {
  schemes: BoardStyleSchemeOption[];
  isGenerating: boolean;
  error: string | null;
  lastRequest: string;
  generateSchemes: (request?: string) => Promise<void>;
  previewScheme: (scheme: BoardStyleSchemeOption) => void;
  clearPreview: () => void;
  applyScheme: (scheme: BoardStyleSchemeOption) => void;
  clearError: () => void;
}

export function useBoardStyleOptimization({
  board,
  targetElements,
  selectionSummary,
  autoGenerate = false,
}: UseBoardStyleOptimizationOptions): UseBoardStyleOptimizationResult {
  const [schemes, setSchemes] = useState<BoardStyleSchemeOption[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [lastRequest, setLastRequest] = useState('');
  const autoGeneratedSelectionKeyRef = useRef<string | null>(null);
  const previewSnapshotRef = useRef<ReturnType<typeof createStyleSnapshot> | null>(null);
  const previewSchemeIdRef = useRef<string | null>(null);

  const selectionKey = useMemo(
    () =>
      targetElements
        .map((element) => (element as Record<string, unknown>)['id'])
        .filter((id): id is string => typeof id === 'string')
        .sort()
        .join('|'),
    [targetElements]
  );

  const clearPreview = useCallback(() => {
    if (!previewSnapshotRef.current) {
      previewSchemeIdRef.current = null;
      return;
    }

    restoreStyleSnapshot(board, previewSnapshotRef.current, {
      saveToHistory: false,
    });
    previewSnapshotRef.current = null;
    previewSchemeIdRef.current = null;
  }, [board]);

  const setApplyError = useCallback((reason: unknown) => {
    const message = reason instanceof Error ? reason.message : '应用样式失败';
    setError(`应用样式失败：${message}`);
  }, []);

  useEffect(() => {
    clearPreview();
    setSchemes([]);
    setError(null);
    setLastRequest('');
    autoGeneratedSelectionKeyRef.current = null;
  }, [clearPreview, selectionKey]);

  useEffect(() => {
    return () => {
      clearPreview();
    };
  }, [clearPreview]);

  const generateSchemes = useCallback(
    async (request: string = '') => {
      if (!targetElements.length) {
        setSchemes([]);
        return;
      }

      setIsGenerating(true);
      setError(null);
      setLastRequest(request);

      try {
        const nextSchemes = await boardStyleService.generateMultipleSchemes(
          board,
          targetElements,
          request,
          3,
          selectionSummary
        );
        setSchemes(nextSchemes);
      } catch (reason) {
        setError(reason instanceof Error ? reason.message : '生成样式方案失败');
      } finally {
        setIsGenerating(false);
      }
    },
    [board, selectionSummary, targetElements]
  );

  useEffect(() => {
    if (!autoGenerate || !targetElements.length || schemes.length > 0 || isGenerating) {
      return;
    }

    if (autoGeneratedSelectionKeyRef.current === selectionKey) {
      return;
    }

    autoGeneratedSelectionKeyRef.current = selectionKey;
    void generateSchemes();
  }, [autoGenerate, generateSchemes, isGenerating, schemes.length, selectionKey, targetElements.length]);

  const previewScheme = useCallback(
    (scheme: BoardStyleSchemeOption) => {
      if (!targetElements.length || previewSchemeIdRef.current === scheme.id) {
        return;
      }

      clearPreview();
      const snapshot = createStyleSnapshot(targetElements);
      previewSnapshotRef.current = snapshot;
      try {
        applyStyleToElements(board, targetElements, scheme.styles, {
          saveToHistory: false,
        });
        previewSchemeIdRef.current = scheme.id;
      } catch (reason) {
        previewSnapshotRef.current = null;
        previewSchemeIdRef.current = null;
        restoreStyleSnapshot(board, snapshot, {
          saveToHistory: false,
        });
        setApplyError(reason);
      }
    },
    [board, clearPreview, setApplyError, targetElements]
  );

  const applyScheme = useCallback(
    (scheme: BoardStyleSchemeOption) => {
      clearPreview();
      if (!targetElements.length) {
        return;
      }
      const snapshot = createStyleSnapshot(targetElements);
      try {
        applyStyleToElements(board, targetElements, scheme.styles);
      } catch (reason) {
        restoreStyleSnapshot(board, snapshot, {
          saveToHistory: false,
        });
        setApplyError(reason);
      }
    },
    [board, clearPreview, setApplyError, targetElements]
  );

  return {
    schemes,
    isGenerating,
    error,
    lastRequest,
    generateSchemes,
    previewScheme,
    clearPreview,
    applyScheme,
    clearError: () => setError(null),
  };
}
